// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCVWxqljLd36t1jKr5E0CKfI_QTE62SU',
    appId: '1:539847385705:web:3a2d25cd0960935daf38f8',
    messagingSenderId: '539847385705',
    projectId: 'remotevision-b5796',
    authDomain: 'remotevision-b5796.firebaseapp.com',
    storageBucket: 'remotevision-b5796.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRSIf3Ap6-wV1yWdB_8raNfANksse08cM',
    appId: '1:539847385705:android:9bfb4c4709009cc4af38f8',
    messagingSenderId: '539847385705',
    projectId: 'remotevision-b5796',
    storageBucket: 'remotevision-b5796.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTGmnuS-4aoZtrujYlOLw-Q18sQ6SLPQ',
    appId: '1:539847385705:ios:accaf8c8f33c370baf38f8',
    messagingSenderId: '539847385705',
    projectId: 'remotevision-b5796',
    storageBucket: 'remotevision-b5796.appspot.com',
    iosBundleId: 'com.example.remotevision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWTGmnuS-4aoZtrujYlOLw-Q18sQ6SLPQ',
    appId: '1:539847385705:ios:accaf8c8f33c370baf38f8',
    messagingSenderId: '539847385705',
    projectId: 'remotevision-b5796',
    storageBucket: 'remotevision-b5796.appspot.com',
    iosBundleId: 'com.example.remotevision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkCVWxqljLd36t1jKr5E0CKfI_QTE62SU',
    appId: '1:539847385705:web:226b62ba2336e0efaf38f8',
    messagingSenderId: '539847385705',
    projectId: 'remotevision-b5796',
    authDomain: 'remotevision-b5796.firebaseapp.com',
    storageBucket: 'remotevision-b5796.appspot.com',
  );
}